### ISSUE TITLE
[建议]增加快捷键绑定和将cnblog的帐号信息配置在配置文件

### ISSUE THREAD

**Issue by dingguotao** [kotcmm/writecnblog#1]
如题，作者开源的插件，很好用。但是可以适当做些改善，用起来就更加方便。 

- 增加快捷键绑定
- 将cnblog的帐号信息配置在配置文件

**Comment by nkbai** [comment]
可否做一个大包插件,发布到vscode的market呢,感觉作者已经放弃维护了.

**Comment by GuojieLin** [comment]
> 
> 
> 如题，作者开源的插件，很好用。但是可以适当做些改善，用起来就更加方便。
> 
>     * 增加快捷键绑定
> 
>     * 将cnblog的帐号信息配置在配置文件
新的版本已经支持通过shift+i快捷键选择图片，同时将账号信息保存到配置中了，不必每次输入。

**Comment by kotcmm** [comment]
已经发布了0.1.0
