### ISSUE TITLE
重新设置工作空间后报错

### ISSUE THREAD

**Issue by sorcierdw** [kotcmm/writecnblog#13]
![图片](https://user-images.githubusercontent.com/35890564/71777212-c3f04900-2fd7-11ea-8c8d-50d96e6693bc.png)

**Comment by liaggh** [comment]
ENOENT: no such file or directory, open 'D:\AdminNote\admin_blog\.cnblog\index'

**Comment by sorcierdw** [comment]
ENOENT: no such file or directory, open 'D:\AdminNote\admin_blog\.cnblog\index'

**Comment by kotcmm** [comment]
你是怎么重新设置工作空间的呢？我自己去设置里面重新设置了blog workspace的路径，然后重新拉取文章并没有报错。你提供一下是怎么操作的，我好重现一下

**Comment by sorcierdw** [comment]
将第一次设置的blog workspace路径为D:\AdminNote 里的内容全删了，然后在VScode 里修改新的blog workspace路径为：D:\AdminNote\admin_blog，提交文章的时候就会报这个错。

**Comment by sorcierdw** [comment]
后来重装了插件并将C:\Users\用户\.vscode目录删掉就好了。但是提交文章的时候“Cannot read property ForEach of undefined” 的错误还是会提示。

**Comment by kotcmm** [comment]
第一次设置工作空间的话，会创建一个.cnblog\index文件，如果你删除掉的话，就要重新拉取一下文章，来生成这个文件，如果你博客园里面没有文章的话，是会报错的，这个是bug的。修改了，但是没有发布新的插件。把.cnblog\index这个文件删除掉是不行的。
