### ISSUE TITLE
大佬插件还维护吗?博客标题中存在不符合windows文件名的字符时,同步出错

### ISSUE THREAD

**Issue by FalleverX** [kotcmm/writecnblog#24]
![image](https://user-images.githubusercontent.com/15180187/102955381-bac1fa00-4510-11eb-9ac4-8498de354702.png)
一直用这个插件写MD博客,很方便.有个问题是:博客标题中存在不符合windons文件名的字符时,就同步出错了.能不能本地文件名做下处理,能正常同步.

另外希望加个 清除本地重新同步的功能, 因为在2个电脑上使用,很容易出面M标记的文件.

谢谢 大佬

**Comment by kotcmm** [comment]
代码加上去了，等有时间再测看看
这些怎么改都是会有点问题，例如 win系统的文件名不允许，`\ / : * ? \ < > |` 这些字符，
问题1：其中 * 号用encodeURIComponent也是无法转义的。
问题2：如果标题包含了这些字符的转义，那么读出的时候，会把原本的标题改变 例如 ：**我是标题%5c后续** 。那读出来就会把它变成 **我是标题\后续** ，所以这些情况下，还是导致预期结果不一样
