### ISSUE TITLE
拉取文章报错

### ISSUE THREAD

**Issue by Higurashi-kagome** [kotcmm/writecnblog#29]
很方便，谢谢！

我发现当文章标题中包含斜杠或反斜杠时，拉取文章会报错：

<details>
<summary>文章标题</summary>

![image](https://user-images.githubusercontent.com/51501079/131783228-1cd179fd-c399-4951-bd1d-95f4a070f26f.png)

</details>

<details>
<summary>报错</summary>

![image](https://user-images.githubusercontent.com/51501079/131783067-0e5b5949-9e9b-4462-83e1-a09004559980.png)

</details>

**Comment by kotcmm** [comment]
[之前有人提过](https://github.com/kotcmm/writecnblog/issues/24)，暂时没有什么其他好的思路。除非换成本地缓不要存标题名称

**Comment by Higurashi-kagome** [comment]
或许的确需要在本地改变名称并且记录本地与远程的差别，那样至少不会报错。我将会尝试解决该问题。

**Comment by Higurashi-kagome** [comment]
初步的想法是使用 front-matter 来记录博文的标题（像 Hexo 那样）。

**Comment by kotcmm** [comment]
> 初步的想法是使用 front-matter 来记录博文的标题（像 Hexo 那样）。

只要是不要标题来存储成文件基本都是可以解决这个问题的，不过我现在确实比较难抽出时间来改，也不知道我要拖到什么时候。

**Comment by Higurashi-kagome** [comment]
嗯，我前几天有查看过源码，发现有些内容不太能读懂。我应该会在下周日和下周一继续尝试完善，如果可以的话，我将会在遇到比较难以解决的问题时在 QQ 群中提问。

**Comment by Higurashi-kagome** [comment]
限于我目前的水平和时间，我想我应该不会尝试完善该 Issue 中的问题了。Cnblogs 官方做了类似的插件 [vscode-cnb](https://github.com/cnblogs/vscode-cnb)，初步观察要更加完善。
