### ISSUE TITLE
writeCnblog.blogName: 博客园的Blog地址名

### ISSUE THREAD

**Issue by nkbai** [kotcmm/writecnblog#5]
这个该填写什么呢?
我的博客地址是 http://www.cnblogs.com/baizx/
无论我填写http://www.cnblogs.com/baizx/还是 baizx都是错的,无法发布博客

**Comment by kotcmm** [comment]
在博客园-》管理-》设置  里面有个  Blog地址名：******** (更改Blog地址名会让以前的文章链接失效，请不要轻易修改，这个********就是了

**Comment by nkbai** [comment]
谢谢,可以发表博客了,但是发布成功以后没有提示,并且不修改文件名,导致无法判断成功与否,
我用的是0.0.5版本 vscode 市场上安装的

**Comment by kotcmm** [comment]
发布了0.1.0现在用起来相对方便一些了
